name: PostDeploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    branches: ["main"]
    types: [completed]

env:
  SITEMAP_URL: "http://zuralski.net/sitemap.xml"
  RUBY_VERSION: 2.7.5

jobs:
  validate_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Check status
        run: curl --location --fail $SITEMAP_URL

  # purge_cache_cloudflare:
  #   runs-on: ubuntu-latest
  #   needs: validate_deployment
  #   if: ${{ success() }}
  #   steps:
  #     - name: Cloudflare Purge Cache
  #       uses: jakejarvis/cloudflare-purge-action@master
  #       env:
  #         CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
  #         CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

  sitemaps_ping:
    runs-on: ubuntu-latest
    needs: validate_deployment
    if: ${{ success() }}
    steps:
      - name: Sitemap URL
        run: echo $SITEMAP_URL
      # - name: Ping Bing
      #   run: |
      #     curl --location --fail https://www.bing.com/ping?sitemap=$SITEMAP_URL
      # - name: Ping Google
      #   run: |
      #     curl --location --fail https://www.google.com/webmasters/tools/ping?sitemap=$SITEMAP_URL